"""Build the body-only Dense index used by the CLI and local search app."""

import argparse
import hashlib
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODEL = "BAAI/bge-m3"


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_chunks(path):
    if not path.is_file():
        raise ValueError(f"청크 파일을 찾을 수 없습니다: {path}")
    chunks = [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
    if not chunks:
        raise ValueError("임베딩을 만들 청크가 없습니다.")
    required = {"chunk_id", "doc_id", "path", "body"}
    if any(not required <= set(chunk) or not isinstance(chunk["body"], str)
           or not chunk["body"].strip() for chunk in chunks):
        raise ValueError("청크에 검색용 필드가 없거나 본문이 비어 있습니다.")
    if len({chunk["chunk_id"] for chunk in chunks}) != len(chunks):
        raise ValueError("중복 청크 ID가 있습니다.")
    return chunks


def make_manifest(model, chunks_path, embedding_path):
    return {
        "model": model,
        "index_text": "body",
        "chunks_sha256": sha256(chunks_path),
        "embedding_sha256": sha256(embedding_path),
        "provenance": "generated by src/build_dense_index.py; body-only index",
    }


def build_index(root=ROOT, model_name=DEFAULT_MODEL, batch_size=8,
                local_files_only=False):
    if batch_size < 1:
        raise ValueError("batch size는 1 이상이어야 합니다.")

    import numpy as np
    from sentence_transformers import SentenceTransformer

    chunks_path = root / "data/processed/chunks.jsonl"
    embedding_path = root / "data/processed/embeddings.npy"
    config_path = root / "config/dense_index.json"
    chunks = read_chunks(chunks_path)

    print(f"모델 로드: {model_name}")
    model = SentenceTransformer(model_name, local_files_only=local_files_only)
    print(f"본문 임베딩 생성: {len(chunks):,}개")
    matrix = np.asarray(model.encode(
        [chunk["body"] for chunk in chunks],
        batch_size=batch_size,
        normalize_embeddings=True,
        show_progress_bar=True,
    ))
    if (matrix.ndim != 2 or len(matrix) != len(chunks)
            or not np.isfinite(matrix).all()
            or not np.allclose(np.linalg.norm(matrix, axis=1), 1, atol=1e-3)):
        raise ValueError("정규화된 임베딩을 생성하지 못했습니다.")

    embedding_path.parent.mkdir(parents=True, exist_ok=True)
    temp_embedding = embedding_path.with_name("embeddings.tmp.npy")
    try:
        np.save(temp_embedding, matrix, allow_pickle=False)
        os.replace(temp_embedding, embedding_path)
    finally:
        temp_embedding.unlink(missing_ok=True)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = make_manifest(model_name, chunks_path, embedding_path)
    temp_config = config_path.with_suffix(".tmp")
    try:
        temp_config.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
        os.replace(temp_config, config_path)
    finally:
        temp_config.unlink(missing_ok=True)

    print(f"임베딩: {embedding_path} ({matrix.shape[0]:,} x {matrix.shape[1]:,})")
    print(f"색인 지문: {config_path}")
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--local-files-only", action="store_true",
                        help="이미 로컬에 저장된 모델만 사용")
    args = parser.parse_args()
    build_index(args.root, args.model, args.batch_size, args.local_files_only)


if __name__ == "__main__":
    main()
